import {CSSProperties} from 'react'

export interface TelegrafPluginAssets {
  id: string
  name: string
  image?: string
  markdown?: string
  style?: CSSProperties
}

export const WRITE_DATA_TELEGRAF_PLUGINS: TelegrafPluginAssets[] = [
  {
    id: 'activemq',
    name: 'ActiveMQ',
    markdown: 'activemq',
    image: 'activemq',
  },
  {
    id: 'aerospike',
    name: 'Aerospike',
    markdown: 'aerospike',
    image: 'aerospike',
  },
  {
    id: 'aliyuncms',
    name: 'Alibaba (Aliyun) CloudMonitor Service Statistics',
    markdown: 'aliyuncms',
    image: 'aliyuncms',
    style: {maxWidth: '150%'},
  },
  {
    id: 'amd_rocm_smi',
    name: 'ROCm System Management Interface',
    markdown: 'amd_rocm_smiMardown',
    image: 'amd_rocm_smi',
  },
  {
    id: 'amqp_consumer',
    name: 'AMQP Consumer',
    markdown: 'amqp_consumer',
    image: 'amqp_consumer',
  },
  {
    id: 'apache',
    name: 'Apache',
    markdown: 'apache',
    image: 'apache',
  },
  {
    id: 'apcupsd',
    name: 'APCUPSD',
    markdown: 'apcupsd',
    image: 'apcupsd',
  },
  {
    id: 'aurora',
    name: 'Aurora',
    markdown: 'aurora',
    image: 'aurora',
  },
  {
    id: 'azure_storage_queue',
    name: 'Azure Storage Queue',
    markdown: 'azure_storage_queue',
    image: 'azure_storage_queue',
  },
  {
    id: 'bcache',
    name: 'bcache',
    markdown: 'bcache',
    image: 'bcache',
  },
  {
    id: 'beanstalkd',
    name: 'Beanstalkd',
    markdown: 'beanstalkd',
    image: 'beanstalkd',
  },
  {
    id: 'beat',
    name: 'Beat',
    markdown: 'beat',
    image: 'beat',
  },
  {
    id: 'bind',
    name: 'BIND 9 Nameserver Statistics',
    markdown: 'bind',
    image: 'bind',
  },
  {
    id: 'bond',
    name: 'Bond',
    markdown: 'bond',
    image: 'bond',
  },
  {
    id: 'burrow',
    name: 'Burrow Kafka Consumer Lag Checking',
    markdown: 'burrow',
    image: 'burrow',
  },
  {
    id: 'cassandra',
    name: 'Cassandra',
    markdown: 'cassandra',
    image: 'cassandra',
  },
  {
    id: 'ceph',
    name: 'Ceph Storage',
    markdown: 'ceph',
    image: 'ceph',
  },
  {
    id: 'cgroup',
    name: 'CGroup',
    markdown: 'cgroup',
    image: 'cgroup',
  },
  {
    id: 'chrony',
    name: 'chrony',
    markdown: 'chrony',
    image: 'chrony',
  },
  {
    id: 'cisco_telemetry_mdt',
    name: 'Cisco Model-Driven Telemetry (MDT)',
    markdown: 'cisco_telemetry_mdt',
    image: 'cisco_telemetry_mdt',
  },
  {
    id: 'clickhouse',
    name: 'ClickHouse',
    markdown: 'clickhouse',
    image: 'clickhouse',
  },
  {
    id: 'cloud_pubsub',
    name: 'Google Cloud PubSub',
    markdown: 'cloud_pubsub',
    image: 'cloud_pubsub',
  },
  {
    id: 'cloud_pubsub_push',
    name: 'Google Cloud PubSub Push',
    markdown: 'cloud_pubsub_push',
    image: 'cloud_pubsub_push',
  },
  {
    id: 'cloudwatch',
    name: 'Amazon CloudWatch Statistics',
    markdown: 'cloudwatch',
    image: 'cloudwatch',
  },
  {
    id: 'conntrack',
    name: 'Conntrack',
    markdown: 'conntrack',
    image: 'conntrack',
  },
  {
    id: 'consul',
    name: 'Consul',
    markdown: 'consul',
    image: 'consul',
  },
  {
    id: 'couchbase',
    name: 'Couchbase',
    markdown: 'couchbase',
    image: 'couchbase',
  },
  {
    id: 'couchdb',
    name: 'CouchDB',
    markdown: 'couchdb',
    image: 'couchdb',
  },
  {
    id: 'cpu',
    name: 'CPU',
    markdown: 'cpu',
    image: 'cpu',
  },
  {
    id: 'csgo',
    name: 'Counter-Strike: Global Offensive (CSGO)',
    markdown: 'csgo',
    image: 'csgo',
  },
  {
    id: 'dcos',
    name: 'DC/OS',
    markdown: 'dcos',
    image: 'dcos',
  },
  {
    id: 'directory_monitor',
    name: 'Directory Monitor',
    markdown: 'directory_monitor',
    image: 'directory_monitor',
  },
  {
    id: 'disk',
    name: 'Disk',
    markdown: 'disk',
    image: 'disk',
  },
  {
    id: 'diskio',
    name: 'DiskIO',
    markdown: 'diskio',
    image: 'diskio',
  },
  {
    id: 'disque',
    name: 'Disque',
    markdown: 'disque',
    image: 'disque',
  },
  {
    id: 'dmcache',
    name: 'DMCache',
    markdown: 'dmcache',
    image: 'dmcache',
  },
  {
    id: 'dns_query',
    name: 'DNS Query',
    markdown: 'dns_query',
    image: 'dns_query',
  },
  {
    id: 'docker',
    name: 'Docker',
    markdown: 'docker',
    image: 'docker',
  },
  {
    id: 'docker_log',
    name: 'Docker Log',
    markdown: 'docker_log',
    image: 'docker_log',
  },
  {
    id: 'dovecot',
    name: 'Dovecot',
    markdown: 'dovecot',
    image: 'dovecot',
  },
  {
    id: 'dpdk',
    name: 'Data Plane Development Kit (DPDK)',
    markdown: 'dpdk',
    image: 'dpdk',
  },
  {
    id: 'ecs',
    name: 'Amazon ECS',
    markdown: 'ecs',
    image: 'ecs',
  },
  {
    id: 'elasticsearch',
    name: 'Elasticsearch',
    markdown: 'elasticsearch',
    image: 'elasticsearch',
  },
  {
    id: 'elasticsearch_query',
    name: 'Elasticsearch Query',
    markdown: 'elasticsearch_query',
    image: 'elasticsearch',
  },
  {
    id: 'ethtool',
    name: 'Ethtool',
    markdown: 'ethtool',
    image: 'ethtool',
  },
  {
    id: 'eventhub_consumer',
    name: 'Event Hub Consumer',
    markdown: 'eventhub_consumer',
    image: 'eventhub_consumer',
  },
  {
    id: 'exec',
    name: 'Exec',
    markdown: 'exec',
    image: 'exec',
  },
  {
    id: 'execd',
    name: 'Execd',
    markdown: 'execd',
    image: 'execd',
  },
  {
    id: 'fail2ban',
    name: 'Fail2ban',
    markdown: 'fail2ban',
    image: 'fail2ban',
  },
  {
    id: 'fibaro',
    name: 'Fibaro',
    markdown: 'fibaro',
    image: 'fibaro',
  },
  {
    id: 'file',
    name: 'File',
    markdown: 'file',
    image: 'file',
  },
  {
    id: 'filecount',
    name: 'Filecount',
    markdown: 'filecount',
    image: 'filecount',
  },
  {
    id: 'filestat',
    name: 'filestat',
    markdown: 'filestat',
    image: 'filestat',
  },
  {
    id: 'fireboard',
    name: 'Fireboard',
    markdown: 'fireboard',
    image: 'fireboard',
  },
  {
    id: 'fluentd',
    name: 'Fluentd',
    markdown: 'fluentd',
    image: 'fluentd',
  },
  {
    id: 'github',
    name: 'GitHub',
    markdown: 'github',
    image: 'github',
  },
  {
    id: 'gnmi',
    name: 'gNMI (gRPC Network Management Interface)',
    markdown: 'gnmi',
    image: 'gnmi',
  },
  {
    id: 'graylog',
    name: 'GrayLog',
    markdown: 'graylog',
    image: 'graylog',
  },
  {
    id: 'haproxy',
    name: 'HAProxy',
    markdown: 'haproxy',
    image: 'haproxy',
  },
  {
    id: 'hddtemp',
    name: 'HDDtemp',
    markdown: 'hddtemp',
    image: 'hddtemp',
  },
  {
    id: 'http',
    name: 'HTTP',
    markdown: 'http',
    image: 'http',
  },
  {
    id: 'http_listener_v2',
    name: 'HTTP Listener v2',
    markdown: 'http_listener_v2',
    image: 'http_listener_v2',
  },
  {
    id: 'http_response',
    name: 'HTTP Response',
    markdown: 'http_response',
    image: 'http_response',
  },
  {
    id: 'httpjson',
    name: 'HTTP JSON',
    markdown: 'httpjson',
    image: 'httpjson',
  },
  {
    id: 'icinga2',
    name: 'Icinga2',
    markdown: 'icinga2',
    image: 'icinga2',
  },
  {
    id: 'infiniband',
    name: 'InfiniBand',
    markdown: 'infiniband',
    image: 'infiniband',
  },
  {
    id: 'influxdb',
    name: 'InfluxDB',
    markdown: 'influxdb',
    image: 'influxdb',
  },
  {
    id: 'influxdb_listener',
    name: 'InfluxDB Listener',
    markdown: 'influxdb_listener',
    image: 'influxdb_listener',
  },
  {
    id: 'influxdb_v2_listener',
    name: 'InfluxDB V2 Listener',
    markdown: 'influxdb_v2_listener',
    image: 'influxdb_v2_listener',
  },
  {
    id: 'intel_powerstat',
    name: 'Intel PowerStat',
    markdown: 'intel_powerstat',
    image: 'intel_powerstat',
  },
  {
    id: 'intel_rdt',
    name: 'Intel RDT',
    markdown: 'intel_rdt',
    image: 'intel_rdt',
  },
  {
    id: 'internal',
    name: 'Telegraf Internal',
    markdown: 'internal',
    image: 'internal',
  },
  {
    id: 'internet_speed',
    name: 'Internet Speed',
    markdown: 'internet_speed',
    image: 'wireless',
  },
  {
    id: 'interrupts',
    name: 'Interrupts',
    markdown: 'interrupts',
    image: 'interrupts',
  },
  {
    id: 'ipmi_sensor',
    name: 'IPMI Sensor',
    markdown: 'ipmi_sensor',
    image: 'ipmi_sensor',
  },
  {
    id: 'ipset',
    name: 'Ipset',
    markdown: 'ipset',
    image: 'ipset',
  },
  {
    id: 'iptables',
    name: 'Iptables',
    markdown: 'iptables',
    image: 'iptables',
  },
  {
    id: 'ipvs',
    name: 'IPVS',
    markdown: 'ipvs',
    image: 'ipvs',
  },
  {
    id: 'jenkins',
    name: 'Jenkins',
    markdown: 'jenkins',
    image: 'jenkins',
  },
  {
    id: 'jolokia',
    name: 'Jolokia',
    markdown: 'jolokia',
    image: 'jolokia',
  },
  {
    id: 'jolokia2',
    name: 'Jolokia2',
    markdown: 'jolokia2',
    image: 'jolokia2',
  },
  {
    id: 'jti_openconfig_telemetry',
    name: 'JTI OpenConfig Telemetry',
    markdown: 'jti_openconfig_telemetry',
    image: 'jti_openconfig_telemetry',
  },
  {
    id: 'kafka_consumer',
    name: 'Kafka Consumer',
    markdown: 'kafka_consumer',
    image: 'kafka_consumer',
  },
  {
    id: 'kafka_consumer_legacy',
    name: 'Kafka Consumer Legacy',
    markdown: 'kafka_consumer_legacy',
    image: 'kafka_consumer_legacy',
  },
  {
    id: 'kapacitor',
    name: 'Kapacitor',
    markdown: 'kapacitor',
    image: 'kapacitor',
  },
  {
    id: 'kernel',
    name: 'Kernel',
    markdown: 'kernel',
    image: 'kernel',
  },
  {
    id: 'kernel_vmstat',
    name: 'Kernel VMStat',
    markdown: 'kernel_vmstat',
    image: 'kernel_vmstat',
  },
  {
    id: 'kibana',
    name: 'Kibana',
    markdown: 'kibana',
    image: 'kibana',
  },
  {
    id: 'kinesis_consumer',
    name: 'Kinesis Consumer',
    markdown: 'kinesis_consumer',
    image: 'kinesis_consumer',
  },
  {
    id: 'knx_listener',
    name: 'KNX',
    markdown: 'knx_listener',
    image: 'knx_listener',
  },
  {
    id: 'kube_inventory',
    name: 'Kubernetes Inventory',
    markdown: 'kube_inventory',
    image: 'kube_inventory',
  },
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    markdown: 'kubernetes',
    image: 'kubernetes',
  },
  {
    id: 'lanz',
    name: 'Arista LANZ Consumer',
    markdown: 'lanz',
    image: 'lanz',
  },
  {
    id: 'leofs',
    name: 'LeoFS',
    markdown: 'leofs',
    image: 'leofs',
  },
  {
    id: 'linux_sysctl_fs',
    name: 'Linux Sysctl FS',
    markdown: 'linux_sysctl_fs',
    image: 'linux_sysctl_fs',
  },
  {
    id: 'logparser',
    name: 'Logparser',
    markdown: 'logparser',
    image: 'logparser',
  },
  {
    id: 'logstash',
    name: 'Logstash',
    markdown: 'logstash',
    image: 'logstash',
  },
  {
    id: 'lustre2',
    name: 'Lustre',
    markdown: 'lustre2',
    image: 'lustre2',
  },
  {
    id: 'mailchimp',
    name: 'Mailchimp',
    markdown: 'mailchimp',
    image: 'mailchimp',
  },
  {
    id: 'marklogic',
    name: 'MarkLogic',
    markdown: 'marklogic',
    image: 'marklogic',
  },
  {
    id: 'mcrouter',
    name: 'Mcrouter',
    markdown: 'mcrouter',
    image: 'mcrouter',
  },
  {
    id: 'mdstat',
    name: 'Mdstat',
    markdown: 'mdstat',
    image: 'linux_sysctl_fs',
  },
  {
    id: 'mem',
    name: 'Memory',
    markdown: 'mem',
    image: 'mem',
  },
  {
    id: 'memcached',
    name: 'Memcached',
    markdown: 'memcached',
    image: 'memcached',
  },
  {
    id: 'mesos',
    name: 'Mesos',
    markdown: 'mesos',
    image: 'mesos',
  },
  {
    id: 'minecraft',
    name: 'Minecraft',
    markdown: 'minecraft',
    image: 'minecraft',
  },
  {
    id: 'modbus',
    name: 'Modbus',
    markdown: 'modbus',
    image: 'modbus',
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    markdown: 'mongodb',
    image: 'mongodb',
  },
  {
    id: 'monit',
    name: 'Monit',
    markdown: 'monit',
    image: 'monit',
  },
  {
    id: 'mqtt_consumer',
    name: 'MQTT Consumer',
    markdown: 'mqtt_consumer',
    image: 'mqtt_consumer',
  },
  {
    id: 'multifile',
    name: 'Multifile',
    markdown: 'multifile',
    image: 'multifile',
  },
  {
    id: 'mysql',
    name: 'MySQL',
    markdown: 'mysql',
    image: 'mysql',
  },
  {
    id: 'nats',
    name: 'NATS',
    markdown: 'nats',
    image: 'nats',
  },
  {
    id: 'nats_consumer',
    name: 'NATS Consumer',
    markdown: 'nats_consumer',
    image: 'nats_consumer',
  },
  {
    id: 'neptune_apex',
    name: 'Neptune Apex',
    markdown: 'neptune_apex',
    image: 'neptune_apex',
  },
  {
    id: 'net_response',
    name: 'Network Response',
    markdown: 'net_response',
    image: 'net_response',
  },
  {
    id: 'netstat',
    name: 'Net Stat',
    markdown: 'netstat',
    image: 'net_response',
  },
  {
    id: 'net',
    name: 'Net',
    markdown: 'net',
    image: 'net_response',
  },
  {
    id: 'nfsclient',
    name: 'NFS Client',
    markdown: 'nfsclient',
    image: 'nfsclient',
  },
  {
    id: 'nginx',
    name: 'Nginx',
    markdown: 'nginx',
    image: 'nginx',
  },
  {
    id: 'nginx_plus',
    name: 'Nginx Plus',
    markdown: 'nginx_plus',
    image: 'nginx_plus',
  },
  {
    id: 'nginx_plus_api',
    name: 'Nginx Plus API',
    markdown: 'nginx_plus_api',
    image: 'nginx_plus_api',
  },
  {
    id: 'nginx_sts',
    name: 'Nginx Stream STS',
    markdown: 'nginx_sts',
    image: 'nginx_sts',
  },
  {
    id: 'nginx_upstream_check',
    name: 'Nginx Upstream Check',
    markdown: 'nginx_upstream_check',
    image: 'nginx_upstream_check',
  },
  {
    id: 'nginx_vts',
    name: 'Nginx Virtual Host Traffic (VTS)',
    markdown: 'nginx_vts',
    image: 'nginx_vts',
  },
  {
    id: 'nsd',
    name: 'NSD',
    markdown: 'nsd',
    image: 'nsd',
  },
  {
    id: 'nsq',
    name: 'NSQ',
    markdown: 'nsq',
    image: 'nsq',
  },
  {
    id: 'nsq_consumer',
    name: 'NSQ Consumer',
    markdown: 'nsq_consumer',
    image: 'nsq_consumer',
  },
  {
    id: 'nstat',
    name: 'Nstat',
    markdown: 'nstat',
    image: 'nstat',
  },
  {
    id: 'ntpq',
    name: 'ntpq',
    markdown: 'ntpq',
    image: 'ntpq',
  },
  {
    id: 'nvidia_smi',
    name: 'Nvidia System Management Interface (SMI)',
    markdown: 'nvidia_smi',
    image: 'nvidia_smi',
  },
  {
    id: 'opcua',
    name: 'OPC UA Client',
    markdown: 'opcua',
    image: 'opcua',
  },
  {
    id: 'openldap',
    name: 'OpenLDAP',
    markdown: 'openldap',
    image: 'openldap',
  },
  {
    id: 'openntpd',
    name: 'OpenNTPD',
    markdown: 'openntpd',
    image: 'openntpd',
  },
  {
    id: 'opensmtpd',
    name: 'OpenSMTPD',
    markdown: 'opensmtpd',
    image: 'opensmtpd',
  },
  {
    id: 'opentelemetry',
    name: 'OpenTelemetry',
    markdown: 'opentelemetry',
    image: 'opentelemetry',
  },
  {
    id: 'openweathermap',
    name: 'OpenWeatherMap',
    markdown: 'openweathermap',
    image: 'openweathermap',
  },
  {
    id: 'passenger',
    name: 'Passenger',
    markdown: 'passenger',
    image: 'passenger',
  },
  {
    id: 'pf',
    name: 'PF',
    markdown: 'pf',
    image: 'pf',
  },
  {
    id: 'pgbouncer',
    name: 'PgBouncer',
    markdown: 'pgbouncer',
    image: 'pgbouncer',
  },
  {
    id: 'phpfpm',
    name: 'PHP-FPM',
    markdown: 'phpfpm',
    image: 'phpfpm',
  },
  {
    id: 'ping',
    name: 'Ping',
    markdown: 'ping',
    image: 'ping',
  },
  {
    id: 'postfix',
    name: 'Postfix',
    markdown: 'postfix',
    image: 'postfix',
  },
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    markdown: 'postgresql',
    image: 'postgresql',
  },
  {
    id: 'postgresql_extensible',
    name: 'PostgreSQL Extensible',
    markdown: 'postgresql_extensible',
    image: 'postgresql_extensible',
  },
  {
    id: 'powerdns',
    name: 'PowerDNS',
    markdown: 'powerdns',
    image: 'powerdns',
  },
  {
    id: 'powerdns_recursor',
    name: 'PowerDNS Recursor',
    markdown: 'powerdns_recursor',
    image: 'powerdns_recursor',
  },
  {
    id: 'processes',
    name: 'Processes',
    markdown: 'processes',
    image: 'processes',
  },
  {
    id: 'procstat',
    name: 'Procstat',
    markdown: 'procstat',
    image: 'procstat',
  },
  {
    id: 'prometheus',
    name: 'Prometheus',
    markdown: 'prometheus',
    image: 'prometheus',
  },
  {
    id: 'proxmox',
    name: 'Proxmox',
    markdown: 'proxmox',
    image: 'proxmox',
  },
  {
    id: 'puppetagent',
    name: 'PuppetAgent',
    markdown: 'puppetagent',
    image: 'puppetagent',
  },
  {
    id: 'rabbitmq',
    name: 'RabbitMQ',
    markdown: 'rabbitmq',
    image: 'rabbitmq',
  },
  {
    id: 'raindrops',
    name: 'Raindrops',
    markdown: 'raindrops',
    image: 'raindrops',
  },
  {
    id: 'ras',
    name: 'RAS Daemon',
    markdown: 'ras',
    image: 'ras',
  },
  {
    id: 'ravendb',
    name: 'RavenDB',
    markdown: 'ravendb',
    image: 'ravendb',
  },
  {
    id: 'redfish',
    name: 'Redfish',
    markdown: 'redfish',
    image: 'redfish',
  },
  {
    id: 'redis',
    name: 'Redis',
    markdown: 'redis',
    image: 'redis',
  },
  {
    id: 'rethinkdb',
    name: 'RethinkDB',
    markdown: 'rethinkdb',
    image: 'rethinkdb',
  },
  {
    id: 'riak',
    name: 'Riak',
    markdown: 'riak',
    image: 'riak',
  },
  {
    id: 'riemann_listener',
    name: 'Riemann Listener',
    markdown: 'riemann_listener',
    image: 'riemann_listener',
  },
  {
    id: 'salesforce',
    name: 'Salesforce',
    markdown: 'salesforce',
    image: 'salesforce',
  },
  {
    id: 'sensors',
    name: 'LM Sensors',
    markdown: 'sensors',
    image: 'sensors',
  },
  {
    id: 'sflow',
    name: 'SFlow',
    markdown: 'sflow',
    image: 'sflow',
  },
  {
    id: 'smart',
    name: 'S.M.A.R.T.',
    markdown: 'smart',
    image: 'smart',
  },
  {
    id: 'snmp',
    name: 'SNMP',
    markdown: 'snmp',
    image: 'snmp',
  },
  {
    id: 'snmp_legacy',
    name: 'SNMP Legacy',
    markdown: 'snmp_legacy',
    image: 'snmp_legacy',
  },
  {
    id: 'snmp_trap',
    name: 'SNMP Trap',
    markdown: 'snmp_trap',
    image: 'snmp_trap',
  },
  {
    id: 'socket_listener',
    name: 'Socket Listener',
    markdown: 'socket_listener',
    image: 'socket_listener',
  },
  {
    id: 'solr',
    name: 'Solr',
    markdown: 'solr',
    image: 'solr',
  },
  {
    id: 'sql',
    name: 'SQL',
    markdown: 'sql',
    image: 'sql',
  },
  {
    id: 'sqlserver',
    name: 'SQL Server',
    markdown: 'sqlserver',
    image: 'sqlserver',
  },
  {
    id: 'stackdriver',
    name: 'Stackdriver Google Cloud Monitoring',
    markdown: 'stackdriver',
    image: 'stackdriver',
  },
  {
    id: 'statsd',
    name: 'StatsD',
    markdown: 'statsd',
    image: 'statsd',
  },
  {
    id: 'suricata',
    name: 'Suricata',
    markdown: 'suricata',
    image: 'suricata',
  },
  {
    id: 'swap',
    name: 'Swap',
    markdown: 'swap',
    image: 'swap',
  },
  {
    id: 'synproxy',
    name: 'Synproxy',
    markdown: 'synproxy',
    image: 'synproxy',
  },
  {
    id: 'syslog',
    name: 'Syslog',
    markdown: 'syslog',
    image: 'syslog',
  },
  {
    id: 'sysstat',
    name: 'sysstat',
    markdown: 'sysstat',
    image: 'sysstat',
  },
  {
    id: 'system',
    name: 'System',
    markdown: 'system',
    image: 'system',
  },
  {
    id: 'systemd_units',
    name: 'systemd Units',
    markdown: 'systemd_units',
    image: 'systemd_units',
  },
  {
    id: 'tail',
    name: 'Tail',
    markdown: 'tail',
    image: 'tail',
  },
  {
    id: 'tcp_listener',
    name: 'TCP Listener',
    markdown: 'tcp_listener',
    image: 'tcp_listener',
  },
  {
    id: 'teamspeak',
    name: 'Teamspeak 3',
    markdown: 'teamspeak',
    image: 'teamspeak',
  },
  {
    id: 'temp',
    name: 'Temperature',
    markdown: 'temp',
    image: 'temp',
  },
  {
    id: 'tengine',
    name: 'Tengine',
    markdown: 'tengine',
    image: 'tengine',
  },
  {
    id: 'tomcat',
    name: 'Tomcat',
    markdown: 'tomcat',
    image: 'tomcat',
  },
  {
    id: 'trig',
    name: 'Trig',
    markdown: 'trig',
    image: 'mem',
  },
  {
    id: 'twemproxy',
    name: 'Twemproxy',
    markdown: 'twemproxy',
    image: 'twemproxy',
  },
  {
    id: 'udp_listener',
    name: 'UDP Listener',
    markdown: 'udp_listener',
    image: 'udp_listener',
  },
  {
    id: 'unbound',
    name: 'Unbound',
    markdown: 'unbound',
    image: 'unbound',
  },
  {
    id: 'uwsgi',
    name: 'uWSGI',
    markdown: 'uwsgi',
    image: 'uwsgi',
  },
  {
    id: 'varnish',
    name: 'Varnish',
    markdown: 'varnish',
    image: 'varnish',
  },
  {
    id: 'vsphere',
    name: 'VMware vSphere',
    markdown: 'vsphere',
    image: 'vsphere',
  },
  {
    id: 'webhooks',
    name: 'Webhooks',
    markdown: 'webhooks',
    image: 'webhooks',
  },
  {
    id: 'win_eventlog',
    name: 'Windows Eventlog',
    markdown: 'win_eventlog',
    image: 'win_eventlog',
  },
  {
    id: 'win_perf_counters',
    name: 'Windows Performance Counters',
    markdown: 'win_perf_counters',
    image: 'win_perf_counters',
  },
  {
    id: 'win_services',
    name: 'Windows Services',
    markdown: 'win_services',
    image: 'win_services',
  },
  {
    id: 'wireguard',
    name: 'Wireguard',
    markdown: 'wireguard',
    image: 'wireguard',
  },
  {
    id: 'wireless',
    name: 'Wireless',
    markdown: 'wireless',
    image: 'wireless',
  },
  {
    id: 'x509_cert',
    name: 'x509 Certificate',
    markdown: 'x509_cert',
    image: 'x509_cert',
  },
  {
    id: 'zfs',
    name: 'ZFS',
    markdown: 'zfs',
    image: 'zfs',
  },
  {
    id: 'zipkin',
    name: 'Zipkin',
    markdown: 'zipkin',
    image: 'zipkin',
  },
  {
    id: 'zookeeper',
    name: 'Zookeeper',
    markdown: 'zookeeper',
    image: 'zookeeper',
  },
]

export const search = (term: string): TelegrafPluginAssets[] =>
  WRITE_DATA_TELEGRAF_PLUGINS.filter(item =>
    item.name.toLowerCase().includes(term.toLowerCase())
  ).sort((a, b) => a.name.toLowerCase().localeCompare(b.name.toLowerCase()))
